name: hotelifoz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_staggered_grid_view: ^0.6.2
  hive: ^2.2.3
  path_provider: ^2.0.14
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  uuid: ^3.0.7
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  flutter_animate: ^4.1.1+1
  flutter_launcher_icons: ^0.13.1
  photo_view: ^0.14.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_light.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/dataset/traveloka.json
    - assets/images/
    - assets/images/payment/
    - assets/icons/