// Mocks generated by Mockito 5.4.0 from annotations
// in hotelifoz/test/features/home/model/services/hotel_local_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hotelifoz/features/home/model/models/hotel_response_model.dart'
    as _i4;
import 'package:hotelifoz/features/home/model/services/hotel_local_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HotelLocalServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelLocalServiceImpl extends _i1.Mock
    implements _i2.HotelLocalServiceImpl {
  MockHotelLocalServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.HotelResponseModel>> getHotels() => (super.noSuchMethod(
        Invocation.method(
          #getHotels,
          [],
        ),
        returnValue: _i3.Future<List<_i4.HotelResponseModel>>.value(
            <_i4.HotelResponseModel>[]),
      ) as _i3.Future<List<_i4.HotelResponseModel>>);
}
